### ISSUE TITLE
2020. 08. 07 (금) 회의 : 업무 분담 및 마스터브랜치

### ISSUE THREAD

**Issue by SejinHan25** [Bit159/synergy#12]
1. 오늘까지 작업한 내용
- 세진님 : 시큐리티 인증 및 권한 처리
- 하진님 : 시큐리티 자동 로그인
- 근형님 : 시큐리티 자동 로그인, 메인 페이지 작업중 전체적인 틀 정도만 구현
- 형중님 : sql 스케줄러, 트리거 관련 정보 검색
- 병주님 : 소셜 로그인 시큐리티와 접목 작업중, 관련 서적 보면서 작업 진행중

[업무 분담]
- 병주님 : 시큐리티 전담 역할/ 시큐리티 끝나면 채팅과 관련된 기능과 ui 구현(리액트 공부) 
- 근형님 : 프론트 최종 책임자/ 프론트 관련 내용은 근형님의 컨펌 받는 쪽으로... / 사이트 컨셉에 맞는 프론트 구성/ 메인, 로그인, 회원가입 페이지 담당
- 형중님 : 서버 및 DB instance/ 매칭, 삭제, 메인 관련 부분/ 여유가 있다면 안드로이드 웹페이지 매칭 구현하여 푸시기능까지 (예상 3일정도)
- 하진님 : 쪽지, 댓글, 위시 리스트 추가 알림 기능 구현/ 실시간 알림, 게시판
- 세진님 : 게시판 ui, 게시판 프론트

[마스터 브랜치]
병주님 것을 마스터로 올리는 것 -> 병주님 프로젝트 구조 및 변수명 따라갈 것

**Comment by HJ-Rich** [comment]
금일 front 합의내용입니다


width : 1280px;
navbar font-size : 13pt;
navbar font-weight : 550;
navbar welcome 페이지만 픽스.
navbar 위 div height 30px
navbar height 70px
navbar 5 0
logo img width:155px height:55px

햄버거 우상단
메뉴 노출 모바일 60% PC 30%
 
마이페이지 : 하진님
상단 네브바 동일하고
1280px div 잡아서
aside, content %로 width 잡기

웰컴 : 근형님
웰컴은 네브바 픽스 

세진님 : 게시판 컨셉 제시

형중 : css 스타일 다른 버전 제시


로그인시 항상 나올 버튼 리스트
1)마이페이지로 가는 사람 버튼
2)알림종
3)우하단 fixed 그룹채팅

의사소통 수단 : 사이트 내 채팅
