### ISSUE TITLE
2020-08-13 회의

### ISSUE THREAD

**Issue by ecosky23** [Bit159/synergy#16]
지금까지 한 작업
1. 병주 : 시큐리티 작업, 소셜 로그인, 채팅 구현
2. 근형 : 모집글 등록 창,  db작업
3. 하진 :  myPage 비밀번호 변경, 회원탈퇴, 닉네임 변경, 관리자 페이지
4. 세진 : 외부 스터디 글 크롤링 이후 게시판 작성 
5. 형준 : 컬럼 추가, ajax처리, 알림처리

할 작업
1. 병주 : 시큐리티 작업 리팩토리, 채팅창 기록 남게하기
2. 근형 : 모집게시판 db작업
3. 하진 :  관리자 게시판 aside작업, 회원 강퇴 기능
4. 세진 : 외부 게시판 디자인 
5. 형준 : 삭제처리 진행중, json 크롤링 작업

**Comment by HJ-Rich** [comment]
![image](https://user-images.githubusercontent.com/62681566/90136338-fd2f3980-ddae-11ea-969a-46f22c20231e.png)
![image](https://user-images.githubusercontent.com/62681566/90136637-73cc3700-ddaf-11ea-817f-37d4a40b4941.png)
![image](https://user-images.githubusercontent.com/62681566/90136465-2b147e00-ddaf-11ea-9235-9cc7a1171331.png)

**Comment by HJ-Rich** [comment]
@HJ-Rich @ecosky23 @SejinHan25 @kkh1595 @ByungjooYang 
나중에 이슈목록들 볼때 어느 날짜에 어떤 작업이 이뤄졌는지 알 수 있도록
제목에 구현된 주요한 내용들을 함께 기입해주세요~ 오늘을 예로 들면
2020-08-13 회의 : 소셜로그인, 채팅, 모집글+카드디자인, 크롤게시판, 정보변경, 탈퇴
로 할 수도 있습니다 ㅎㅎ 오늘도 모두 수고하셨어요!
