### ISSUE TITLE
2020-08-14 회의 : 게시판, 자동완성, 회원탈퇴, 시큐리티 인코딩, 통합 페이지 구현 및 주말 작업 목표

### ISSUE THREAD

**Issue by SejinHan25** [Bit159/synergy#17]
- 세진님: 원글 페이지 디자인, 게시판 원글 db연결 구현

- 근형님: 지역 텍스트 창 자동완성 구현 (제이쿼리 오토컴플리트)

- 하진님: 관리자 게시판 회원 탈퇴 버튼 기능 구현

- 병주님: 시큐리티 인코딩, url에 이메일 노출 및 추가정보 입력할때 보안이슈 해결

- 형중님: 통합 페이지 구현, 크롤링 보안 완료, 이모지 db에 들어오도록 구현, db입력 실시간 매칭해서 반응하도록 구현

========================================================

주말 작업 목표

- 세진님: 뷰, 댓글, 디자인 작업

- 근형님: 모집 관련 카드보드 입력, 뷰 작업

- 하진님: 페이징, 검색 작업

- 형중님: ssl인증서 검색, db좌표 지도에 뿌리는 작업

- 병주님: 채팅 구체화 작업, 브랜치 합치는 작업 시작 (스탠다드 잡는 방향)

**Comment by HJ-Rich** [comment]
![image](https://user-images.githubusercontent.com/62681566/90240136-a2a3e500-de63-11ea-8a76-27fe87e30877.png)
![image](https://user-images.githubusercontent.com/62681566/90240221-cb2bdf00-de63-11ea-9738-f51e4a863e35.png)
![image](https://user-images.githubusercontent.com/62681566/90240271-e1d23600-de63-11ea-864a-f87a94d58e03.png)
<video oncontextmenu="return false;" id="myVideo" width="640" controls autoplay>
 <source src="https://i.imgur.com/ozx3xAs.mp4" type="video/mp4">
</video>

**Comment by HJ-Rich** [comment]
<video draggable="false" playsinline="" autoplay="" loop="" class="" style="width: 960px; height: 521px;"><source type="video/mp4" src="https://i.imgur.com/ozx3xAs.mp4"></video>

**Comment by HJ-Rich** [comment]
https://i.imgur.com/ozx3xAs.mp4

**Comment by HJ-Rich** [comment]
![image](https://user-images.githubusercontent.com/62681566/90306095-c53a0a80-df04-11ea-8275-fedd55fb8e61.png)
![image](https://user-images.githubusercontent.com/62681566/90306102-ccf9af00-df04-11ea-9041-92d136d52d57.png)

Cloud Flare를 이용한 https 적용 완료

**Comment by HJ-Rich** [comment]
![image](https://user-images.githubusercontent.com/62681566/90306139-2530b100-df05-11ea-9de8-e13c2be01da2.png)
![image](https://user-images.githubusercontent.com/62681566/90306147-3aa5db00-df05-11ea-94d8-08f961a3e4c9.png)
