### ISSUE TITLE
2020-08-23 회의 : 댓글, 페이징 처리, 카드 보드 들어가기 및 페이징 처리, 매칭 옵션 , 채팅

### ISSUE THREAD

**Issue by ByungjooYang** [Bit159/synergy#21]
다음 회의 8월 24일 오전 11시

해야할 일
1. @kkh1595  근형 : 카드 눌렀을 때 해당페이지로 들어가는것, 페이징 처리, 프론트 작업
2. @SejinHan25  세진 : 댓글 삭제, 페이징 처리, 검색 구현
3. @ecosky23  하진 : 관리자 페이지 차트.js 적용
4. @ByungjooYang  병주 : stomp이용한 채팅방 고도화 작업.
5. @HJ-Rich  형중 : 매칭 시스템 작업.

**Comment by HJ-Rich** [comment]
![2020-08-24](https://user-images.githubusercontent.com/62681566/90990766-fee2d380-e5de-11ea-8bf6-5d869e012497.png)
![2020-08-24 (5)](https://user-images.githubusercontent.com/62681566/90990770-04401e00-e5df-11ea-92c8-0110e124a8af.png)
![2020-08-24 (4)](https://user-images.githubusercontent.com/62681566/90990774-0a35ff00-e5df-11ea-84d6-bc9beb4377ea.png)

**Comment by HJ-Rich** [comment]
돌아버리겠습니다 일단 의도대로 작동하는거 같긴 한데
이게 맞는건지도 모르겠고. 정말 이렇게 짰어야만 하는 건지. 혼자 멍청하게 어렵게 생각한건 아닌지 불확실합니다..
