### ISSUE TITLE
2020-08-24 저녁 6시 회의 매칭, 게시판, 채팅, 관리자 페이지

### ISSUE THREAD

**Issue by ecosky23** [Bit159/synergy#24]
지금 까지 한 일

형중 : 매칭 프로그램 작업 중
근형 : 뷰페이지 작업 중, 댓글 작업, 가입 신청 작업
세진 : 댓글 삭제 부분 진행 중
병주 : 채팅 구현 중
하진 : 관리자 페이지 작업

앞으로 할 일

형중 : 매칭 프로그램 작업 중
근형 : 뷰페이지 작업 중, 댓글 작업, 가입 신청 작업
세진 : 댓글 삭제 부분 진행 중
병주 : 채팅 구현 중
하진 : 관리자 페이지 ui 구현

**Comment by HJ-Rich** [comment]
근형님의 카드뷰
![image](https://user-images.githubusercontent.com/62681566/91114603-42167280-e6c3-11ea-97ac-5490b428db78.png)

하진님의 관리자페이지
![image](https://user-images.githubusercontent.com/62681566/91114619-4cd10780-e6c3-11ea-9237-62e512a1ef3d.png)
