### ISSUE TITLE
 2020.07.28 (화) 회의 + 7.28(수)까지 작업목표

### ISSUE THREAD

**Issue by ByungjooYang** [Bit159/synergy#4]
오늘 진행 결과
1. 로그인, 회원가입 프레임 구현 완료.
2. 메인화면에 gif 적용, 구글 로그인 적용 완

료.
3. 팀원들 반응형 웹 공부

오늘 진행
1. 평가 관련.
 여러 항목을 나눠서 (3~4가지) 평가 후 평균을 내서 저장.
혹은 평가 항목마다 따로 저장하고 관리.

2. MySQL 사용하기.

3. 마이페이지 및 전체적인 프레임 구성 

4.
@HJ-Rich  형중님	 => sqldeveloper에서 aws mysql 서버에 접근하도록 세팅 및 프로퍼티 값 공유,
		      카카오, 깃허브 로그인
@ecosky23  하진님 => 반응형 공부 및 로그인, 회원가입 반응형으로 만들기. 
@kkh1595  근형님  => 반응형 공부 및 학습내용 적용
@ByungjooYang  me => 반응형 공부 및 카카오, 깃허브 로그인, 전체적인 프레임 고기.
		        관리자 페이지. 로그인, 회원가입 영상 공유
@SejinHan25  MC 세진 => 반응형 공부.

![login](https://user-images.githubusercontent.com/65591923/88664662-5f820c00-d118-11ea-94f2-2a5ba3451f74.png)

![join](https://user-images.githubusercontent.com/65591923/88664723-732d7280-d118-11ea-89f8-c00bef123e15.png)

**Comment by HJ-Rich** [comment]
** Oracle SQL Developer 에서 MySQL 접속하기 **

1. 도구 - 환경설정 - 데이터베이스 - 타사 JDBC 드라이버
- mysql-connector-java-5.1.6-bin.jar 파일 항목 추가

![image](https://user-images.githubusercontent.com/62681566/88754231-1faf3900-d199-11ea-893c-0c4a16e05ea1.png)
![image](https://user-images.githubusercontent.com/62681566/88754254-2e95eb80-d199-11ea-8bcb-924d560df00c.png)
[mysql.zip](https://github.com/Bit159/synergy/files/4992422/mysql.zip)


2. 접속 탭에서 초록색 십자가 클릭
- Name : 알아볼 수 있게 + 자유롭게
- 데이터베이스 유형 : MySQL
- 사용자 이름 : jpcnani
- 비밀번호 : bitcamp159 (비밀번호 저장 체크)
- 호스트 이름 : security-db.ci3ttblcjdxh.ap-northeast-2.rds.amazonaws.com
- 포트 : 3306

3. 오라클 MySQL 현재까지 찾은 명령어 차이
용도			오라클			MySQL
현재 시각		 	sysdate			now()
전체 테이블 목록		select * from tab;		show tables;
테이블 컬럼 보기		desc 테이블명;		description 테이블명;
문자 컬럼			VARCHAR2		VARCHAR
null값 대체		nvl(value1, value2)		ifnull(value1, value2)
문자 합치기		|| 또는 concat(value1, value2)	concat(value1, value2)

4. MySQL 명령어 만들어내는 사이트
https://aquerytool.com/

5. 예시

select * from newzipcode 
		where sido=#{sido} 
		and (sigungu like '%'||#{sigungu}||'%' or sigungu is null) 
		and roadname like '%'||#{roadname}||'%'


select * from newzipcode 
		where sido=#{sido} 
		and sigungu like ifnull(concat('%',#{sigungu},'%'),0) 
		and roadname like concat('%',#{roadname},'%')

**Comment by HJ-Rich** [comment]
@ByungjooYang @SejinHan25 @kkh1595 @ecosky23 
mysql jar 파일,   접속방법,   mysql문장 만드는 사이트,    오라클과의 간단한 차이 업로드하였습니다!

**Comment by HJ-Rich** [comment]
포트폴리오 사이트 한번 둘러보세요!
많이 보다 보면 뭐가 좋겠구나 각자 주관이 생길 겁니다! ㅎㅎ


- 제가 생각한 컨셉과 가장 유사한 사이트
- 컨셉 컬러, 드롭다운 메뉴는 별로인듯
- 스크롤 시 애니메이션과 전체 컨셉UI는 심플
- 모바일 팝업메뉴 미구현
- 화이트 7 진보라 3
https://recruitfy.com/


- 기본기 참고할만한 사이트
- 첫 접속 시 글씨 올라오는 애니메이션
- 그 외에는 애니메이션이 없어서 사이트가 정적으로 느껴짐
- 컨셉상 캐릭터가 아닌 사람 사진이 들어갔는데 흥미 떨어짐
- 모바일 팝업메뉴 화면 절반 사용
- 화이트 7 옐로우 2 블랙 1
https://synergytutor.com/#about


- 첫 화면 동영상 효과. 여행 컨셉이라 그런듯,
- 화려하긴 하지만 실제 적용하기에는 쫌.. 깔끔한 게 나을듯.
- Features 에서 호버효과, App Screenshots에서 미니메뉴 굿.
- 맨 아래 Stay Connected 에서 소셜 버튼 디자인도 괜춘한듯
- 모바일 팝업메뉴 화면 전체 사용
- 컨셉 컬러랄 게 없어서 보면 볼수록 지저분하게 느껴짐
https://travelobreak.io/


- 첫 화면부터 스크롤 할 때마다 항상 애니메이션이 있음
- 화면이 동적으로 느껴지긴 하지만 간결하지 않아 부담스러움
- 모바일 팝업메뉴가 유일하게 가로가 아니라 세로로 표현
- 컨셉 컬러 화이트 5 보라색 5 별로인듯
https://pulseagent.co/



- 영진전문대 온라인해커톤 참가팀 Yger의 프로젝트
- 모바일 미대응
- 캐릭터 UI는 효과적인듯. 설명하는 배너도 깔끔
- 애니메이션이 전무해서 사이트가 정적으로 느껴짐
- 지역구 검색을 들어가면 사이트와 동떨어진 느낌
- 업체명 검색은 참고할만할 듯. 단 검색창이 디자인 좀 아쉽
- 크리에이터 란은 깔끔한듯.
- 컨셉 컬러 화이트 6 초록 2 보라 2 - 보라가 영....
http://yss-info.cf/
