### ISSUE TITLE
2020.09.08(화) 회의 : sweetAlert

### ISSUE THREAD

**Issue by ByungjooYang** [Bit159/synergy#44]
한 일
근형 : sweetAlert 적용, 유효성 검사 적용.
세진 : 자유게시판 CRUD. 에러 잡는 중.
병주 : 소셜로그인 로직 정리.
하진 : 마이페이지 닉네임 수정 시 중복체크. 정보 수정 에러 해결.
형중 : 기존 프론트 작업과 캘린더 합치기 작업 중.

할일
근형 : 남은 sweetAlert 적용, 디테일 잡는 중
세진 : 에러 잡고 sweetAlert 적용.
병주 : 구글 로그인 완료하기.
하진 : sweetAlert 적용.
형중 : 기존 프론트 작업과 캘린더 합치기 작업 중.

@HJ-Rich @SejinHan25 @kkh1595 @ByungjooYang @ecosky23

**Comment by HJ-Rich** [comment]
@ByungjooYang 쾌차하십쇼!
